[2024-05-11T09:42:36.438+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T09:42:36.455+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_seasons.load_data manual__2024-05-11T09:42:29.557933+00:00 [queued]>
[2024-05-11T09:42:36.461+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_seasons.load_data manual__2024-05-11T09:42:29.557933+00:00 [queued]>
[2024-05-11T09:42:36.462+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-11T09:42:36.472+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-05-11 09:42:29.557933+00:00
[2024-05-11T09:42:36.481+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-11T09:42:36.482+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-05-11T09:42:36.482+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_seasons', 'load_data', 'manual__2024-05-11T09:42:29.557933+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/get_seasons.py', '--cfg-path', '/tmp/tmpj7v3s3l9']
[2024-05-11T09:42:36.484+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask load_data
[2024-05-11T09:42:36.514+0000] {task_command.py:426} INFO - Running <TaskInstance: get_seasons.load_data manual__2024-05-11T09:42:29.557933+00:00 [running]> on host 713383192ea0
[2024-05-11T09:42:36.583+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_seasons' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T09:42:29.557933+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T09:42:29.557933+00:00'
[2024-05-11T09:42:36.584+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T09:42:36.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T09:42:36.584+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_data() missing 1 required positional argument: 'value'
[2024-05-11T09:42:36.591+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_seasons, task_id=load_data, execution_date=20240511T094229, start_date=20240511T094236, end_date=20240511T094236
[2024-05-11T09:42:36.600+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 297 for task load_data (load_data() missing 1 required positional argument: 'value'; 71)
[2024-05-11T09:42:36.615+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-11T09:42:36.627+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T09:42:36.628+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
