[2024-05-11T16:09:43.593+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T16:09:43.606+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_odds_history.parser manual__2024-05-11T16:09:42.019140+00:00 [queued]>
[2024-05-11T16:09:43.610+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_odds_history.parser manual__2024-05-11T16:09:42.019140+00:00 [queued]>
[2024-05-11T16:09:43.610+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-11T16:09:43.618+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parser> on 2024-05-11 16:09:42.019140+00:00
[2024-05-11T16:09:43.624+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-11T16:09:43.625+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-05-11T16:09:43.625+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_odds_history', 'parser', 'manual__2024-05-11T16:09:42.019140+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/get_odds_history.py', '--cfg-path', '/tmp/tmpdhq0su71']
[2024-05-11T16:09:43.626+0000] {standard_task_runner.py:91} INFO - Job 437: Subtask parser
[2024-05-11T16:09:43.654+0000] {task_command.py:426} INFO - Running <TaskInstance: get_odds_history.parser manual__2024-05-11T16:09:42.019140+00:00 [running]> on host 311b133012af
[2024-05-11T16:09:43.703+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_odds_history' AIRFLOW_CTX_TASK_ID='parser' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T16:09:42.019140+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T16:09:42.019140+00:00'
[2024-05-11T16:09:43.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T16:10:13.857+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-05-11T16:10:13.858+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-11T16:10:13.859+0000] {process_utils.py:132} INFO - Sending 15 to group 65. PIDs of all processes in the group: [65]
[2024-05-11T16:10:13.859+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 65
[2024-05-11T16:10:13.859+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-11T16:10:13.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T16:10:13.865+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/steps/get_odds_last.py", line 39, in parser
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-05-11T16:10:13.869+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20240511T160942, start_date=20240511T160943, end_date=20240511T161013
[2024-05-11T16:10:13.876+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 437 for task parser ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(get_odds_history, parser, manual__2024-05-11T16:09:42.019140+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'parser', 'dag_id': 'get_odds_history', 'run_id': 'manual__2024-05-11T16:09:42.019140+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 5, 11, 16, 9, 43, 606576, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 5, 11, 16, 10, 13, 868726, tzinfo=Timezone('UTC')), 'duration': 30}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 65)
[2024-05-11T16:10:13.885+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=65, status='terminated', exitcode=1, started='16:09:42') (65) terminated with exit code 1
